name: Assertions

on:
  pull_request:
    branches: canary

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update NPM
        run: npm i -g npm@latest

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Docs
        run: |
          cd docs
          npm i

      - name: Lint Docs
        run: |
          cd docs
          npx markdownlint 'docs/**/*.md'

      - name: Install Frontend
        run: |
          cd frontend
          npm i

      - name: Lint Frontend
        run: |
          cd frontend
          npx stylelint '**/*.css'
          npx markdownlint '**/*.md'
          npx eslint '**/*.js'

      - name: Run Frontend Tests
        run: |
          cd frontend
          npx jest
